### ISSUE TITLE
Issue with timezone field

### ISSUE THREAD

**Issue by beNjiox** [davidcelis/geocodio#5]
I think it's more an issue with the service, more than with the gem, but since I'm not sure here's the issue I'm experiencing :

While trying to lookup for this address: '6167 whitworth drive 90035 CA', I have this information returned

```
#<Geocodio::Address:0x007f96a6cd4580 @number=nil, @predirectional=nil, @street=nil, @suffix=nil, @city="Los Angeles", @state="CA", @zip="90005", @latitude="34.059163", @longitude="-118.306892", @timezone=#<Geocodio::Timezone:0x007f96a6cd4238 @name=nil, @utc_offset=0, @observes_dst=false>, @accuracy=0.33, @formatted_address="Los Angeles, CA 90005">
```

Here the issue is that `@utc_offset=0` and `@name=nil` which is wrong.

Here's the snippet I have

``` ruby
geocodio = Geocodio::Client.new
booking_address = geocodio.geocode(['6167 whitworth drive 90035 CA'], fields: %w[timezone]).best

ap booking_address
```

Thanks,

**Comment by davidcelis** [comment]
This issue is pretty old and I haven't been able to reproduce it, so I'm going to close it as stale. If this still happens with some addresses, please let me know!
